Create 7.cpp
MaratMay/323_Maystrenko_2024 pull request #16
Opened 2024-11-10 23:14 UTC by MaratMay

Добрый вечер! Я подойду после пары с вопросом... Ломается установка MPI на polus-e

2024-11-12 00:04 UTC, MaratMay commented
Добрый вечер! Подгрузил в папку DZ_7 репорт по заданию. Немного по другому запускал программу (долго не мог понять,  почему вывода нет), но через нужный постановщик задач. Судя по выходным данным, всё прошло успешно

2024-11-13 14:38 UTC, dimlichmanov requested changes
А выводы по MPI-P?

2024-11-14 09:28 UTC, MaratMay commented
Добрый день! Добавил выводы об MPI-P

2024-11-14 10:13 UTC, dimlichmanov requested changes
Вы такой текст могли написать, и не запуская с mpiP)
Я просил какие-то интересные выводы из результата, который выводит mpiP. 
Типа "доля MPI-времени на операцию MPI_reduce с ростом числа процессов растёт, была 1%, стала 5%".

2024-11-15 08:50 UTC, MaratMay commented
Доброе утро!
Добавил в отчёт график, отражающий зависимость AppTime и MPITime от числа процессов

2024-11-15 10:44 UTC, dimlichmanov approved these changes

2024-11-15 14:20 UTC, merged